### ISSUE TITLE
Compatibility with mongoose 4.0.0

### ISSUE THREAD

**Issue by pcothenet** [codetunnel/mongoose-auto-increment#32]
Hi, I was looking to update mongoose to 4.0.0 but currently getting a peerinvalid error. 
```
npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mongoose-auto-increment@3.2.2 wants mongoose@^3.8.12
```
Any plans to support most recent releases of mongoose?

Thanks!

**Comment by chevex** [comment]
The latest version (3.2.3) should work with Mongoose 4.0.0. Please let me know if you encounter any issues with the latest Mongoose :)

**Comment by Chicooz** [comment]
i am still having this issue 

npm ERR! Linux 3.10.53-56.140.amzn1.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mongoose-auto-increment@4.0.0 wants mongoose@~4.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/testgenius/npm-debug.log
