### ISSUE TITLE
Minor Revision upgrade Needs major Mongoose Upgrade

### ISSUE THREAD

**Issue by nukulb** [codetunnel/mongoose-auto-increment#34]
When changing the Mongoose version to to ~ 4.0.0, you should probably use a major version upgrade.

NPM throws an error in this case if package.json of the client contains

 "mongoose": "~3.8.8",
 "mongoose-auto-increment": "^3.2.0",

Just a recommendation, can be easily worked around but when you should not force a major mongoose upgrade in a minor mongoose-auto-increment upgrade.

**Comment by iaincollins** [comment]
Yeah this behaviour seems incorrect (and Mongoose 4.0 is marked as not for production yet so probably should stick to 3.x for now).

**Comment by jovinbm** [comment]
Sorry, I'm having the same error. How do you fix this?

**Comment by wonderdogone** [comment]
same here?

**Comment by chevex** [comment]
Sorry guys. My mistake. I will take care of this as soon as I'm back from lunch ;)

In the meantime you can simply depend on any version older than the current one.

**Comment by wonderdogone** [comment]
Im  getting this with my package.json as follows?
 "mongoose": "~3.8",
    "mongoose-auto-increment": "^3.0.8",

why would this all of a sudden break?
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package mongoose does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mongoose-auto-increment@3.2.3 wants mongoose@~4.0.0

**Comment by chevex** [comment]
Okay, I reverted back to Mongoose 3.8.12 and pushed a new version up under mongoose-auto-increment@3.2.4. This should remove the dependency on mongoose 4.0 for anyone who runs a simple `npm update`. There is also a mongoose-auto-increment@4.0.0 which uses mongoose 4.0.0 (It's just coincidence that the version is the same as mongoose's latest version).
