### ISSUE TITLE
Can new version of mongoose-auto-increment compatibility with mongoose 3.8.x?

### ISSUE THREAD

**Issue by Sean-Wang** [codetunnel/mongoose-auto-increment#37]
After updating mongoose version from 3.8.x to 4.0.x, we meet abnormal condition (https://github.com/Automattic/mongoose/issues/3100).

So, I have to recover mongoose version from 4.0.x to 3.8.31 in `package.json`. I want to know, if I still use version mongoose 3.8.31, will it affect the work of mongoose-auto-increment?

**Comment by DavidBLynch** [comment]
I've got the same issue, except now mongoose is at 4.1.0.

**Comment by Sean-Wang** [comment]
@DavidBLynch You use 'mongoose-rbac' have the same issue? Mongoose 4.1.0 solve this problem? Thanks.

**Comment by wasifjahangir** [comment]
Anyone able to fix this issue. Mongoose 4.1.0 didn't resolve this problem. i currently have 3.8.8 version

**Comment by chevex** [comment]
See #45
