### ISSUE TITLE
Possible Cannot read property 'count' of null issue

### ISSUE THREAD

**Issue by troyblank** [codetunnel/mongoose-auto-increment#38]
Thanks for the great plugin;
I have encountered a strange issue that I would like to point out. This may not be a problem with your plugin but I am not sure what else it would be.

Using your plugin has worked great for all practical purposes but I have noticed I get an error of `Cannot read property 'count' of null` issue at line 160 of index.js when trying the exact same code with a mocha unit test.

You can reproduce this by using my test here:
https://github.com/troyblank/halfsies/blob/master/test/app/models/user.model.spec.js#L23-L24

and removing the `, order: 0` on line 24 so it reads
`//order given to by-pass strange behavior with mongoose-auto-increment`
`var data = {username: 'troy', password: 'password', provider: 'local'},`

I noticed this issue when searching with no concrete resolution: https://github.com/codetunnel/mongoose-auto-increment/issues/10

Thanks in advance for any time looking into this. My current theory is mocha is moving too fast to index the auto-increment models and thus bad stuff is happening but I am not fully sure.

**Comment by troyblank** [comment]
Closing as I am removing it from my project.

**Comment by vitahlin** [comment]
@troyblank Hello , I got this problem like you did.
How did you resolve it?  Thanks.

**Comment by troyblank** [comment]
@vitahlin I never did :( I just didn't use this plugin. I also don't have access to the repo anymore unfortunately and can't remember the work around with me either.

**Comment by vitahlin** [comment]
@troyblank Thanks anyway.
