### ISSUE TITLE
Start auto-increment from 1 instead of 0

### ISSUE THREAD

**Issue by vinayuttamvemparala** [codetunnel/mongoose-auto-increment#47]
I am using mongoose auto-increment in one of my projects and the auto increment starts at 0 instead of 1.
I have used other relational databases in the past and the increment defaults or starts at 1. I would like to know if there any specific reason for starting with 0?

Thanks.

**Comment by syuilo** [comment]
https://github.com/codetunnel/mongoose-auto-increment#want-that-field-to-start-at-a-different-number-than-zero-or-increment-by-more-than-one

**Comment by vinayuttamvemparala** [comment]
@syuilo Thanks. I totally missed it.

**Comment by menthos984** [comment]
@vinayuttam did it work?

**Comment by vinayuttam** [comment]
@menthos984 yes it did work.
